[package]
name = "transliterator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.9"
fs = "0.0.5"
clap = { version = "4.2.4", features = ["derive"] }
unicode-segmentation = "1.10.1"
